# This workflow builds and lints the Cloud Function

name: Cloud Functions Build and Lint

on: [push]

jobs:
  functions_build_and_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: mv src/databasesecret.ts.example src/databasesecret.ts
      - name: Install Dependencies
        run: npm ci
      - name: Linter
        run: npm run lint
      - name: Build
        run: npm run build
